version: '3'

services:
  nginx-proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    container_name: nginx-proxy-container
    restart: always
    links:
      - front
      - back
    depends_on:
      - front
      - back

  front:
    build:
      context: ./front
    ports:
      - "4200:4200"
    container_name: front-container
    restart: always

  back:
    build:
      context: ./back
    ports:
      - "3000:3000"
    container_name: back-container
    restart: always
    links:
      - database
    depends_on:
      - database
